In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [9]:
import numpy as np
from sklearn.datasets import load_digits

In [10]:
digits = load_digits()

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [13]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\Thinkpad\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [14]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.987037037037037

In [16]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9629629629629629

In [17]:
from sklearn.model_selection import KFold

In [18]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [19]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [20]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [21]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\Thinkpad\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [24]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.987037037037037

In [25]:
get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test)

0.9685185185185186

In [29]:
from sklearn.model_selection import StratifiedKFold

In [31]:
folds = StratifiedKFold(n_splits=3)

In [32]:
s_lr=[]
s_svm=[]
s_rf=[]

In [36]:
for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    s_lr.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    s_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    s_rf.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))

C:\Users\Thinkpad\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Thinkpad\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n

In [37]:
s_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [38]:
s_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [39]:
s_rf

[0.9398998330550918, 0.9432387312186978, 0.9148580968280468]

In [40]:
#short cut

In [42]:
from sklearn.model_selection import cross_val_score

In [44]:
new_s_lr=cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\Thinkpad\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Thinkpad\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n

In [45]:
new_s_lr

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [47]:
new_s_svm=cross_val_score(SVC(),digits.data,digits.target)

In [48]:
new_s_svm

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [50]:
new_s_rf=cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

In [51]:
new_s_rf

array([0.91944444, 0.90833333, 0.95543175, 0.97214485, 0.90250696])