In [34]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv('./dummy.csv')

In [36]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [37]:
dummies = pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [38]:
merged = pd.concat([df,dummies],axis=1)

In [39]:
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [40]:
final = merged.drop(['town','west windsor'],axis=1)

In [41]:
final

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [42]:
from sklearn import linear_model
model = linear_model.LinearRegression()

In [43]:
model.fit(final.drop(['price'],axis=1),final.price)

LinearRegression()

In [44]:
model.predict([[2800,0,1]])

C:\Users\Thinkpad\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

# do same thing using one hot encoder

In [45]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [46]:
#dublicate of df to unchance that original one

In [47]:
df_new = df

In [48]:
new_town = le.fit_transform(df_new.town)

In [49]:
new_town

array([0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1])

In [50]:
df_new.town = new_town

In [51]:
df_new

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [52]:
x = df_new[['town','area']].values

# what values will do? it will convert that df into array

In [53]:
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [54]:
y = df_new.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [55]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categorical_features=[0])

TypeError: __init__() got an unexpected keyword argument 'categorical_features'

In [56]:
ohe.fit_transform(x).toarray()

array([[1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

# code basics one hot encoding sucks just watch indian ai production

In [60]:
oh_enc = OneHotEncoder(sparse=False,drop='first')

In [61]:
oh_enc_array = oh_enc.fit_transform(df[['town']])

In [62]:
oh_enc_array

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [63]:
oh_enc_df = pd.DataFrame(oh_enc_array,columns=['town_robinsville',
       'town_west windsor'])

In [64]:
oh_enc_df

town_robinsville  town_west windsor
0                0.0                0.0
1                0.0                0.0
2                0.0                0.0
3                0.0                0.0
4                0.0                0.0
5                0.0                1.0
6                0.0                1.0
7                0.0                1.0
8                0.0                1.0
9                1.0                0.0
10               1.0                0.0
11               1.0                0.0
12               1.0                0.0

In [66]:
final = pd.concat([df.drop('town',axis=1),oh_enc_df],axis=1)
final

area   price  town_robinsville  town_west windsor
0   2600  550000               0.0                0.0
1   3000  565000               0.0                0.0
2   3200  610000               0.0                0.0
3   3600  680000               0.0                0.0
4   4000  725000               0.0                0.0
5   2600  585000               0.0                1.0
6   2800  615000               0.0                1.0
7   3300  650000               0.0                1.0
8   3600  710000               0.0                1.0
9   2600  575000               1.0                0.0
10  2900  600000               1.0                0.0
11  3100  620000               1.0                0.0
12  3600  695000               1.0                0.0

In [68]:
model = linear_model.LinearRegression()

In [69]:
model.fit(final.drop('price',axis=1),final.price)

LinearRegression()

In [71]:
model.predict([[2800,1,0]])

C:\Users\Thinkpad\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])